// ENGR 102 Group Project

// Import the StateData class
import { StateData } from "./StateDataClass.js";

// State Name, Solar Irradiance
export const stateData = {
  Alaska: new StateData("Alaska", 3.0, 0),
  Alabama: new StateData("Alabama", 4.23, 0),
  Arkansas: new StateData("Arkansas", 4.25, 0),
  Arizona: new StateData("Arizona", 6.5, 0),
  California: new StateData("California", 5.61, 0),
  Colorado: new StateData("Colorado", 5.37, 0),
  Connecticut: new StateData("Connecticut", 4.74, 0),
  DistrictOfColumbia: new StateData("District of Columbia", 4.23, 0),
  Florida: new StateData("Florida", 5.55, 0),
  Georgia: new StateData("Georgia", 4.87, 0),
  Hawaii: new StateData("Hawaii", 6.02, 0),
  Iowa: new StateData("Iowa", 4.4, 0),
  Idaho: new StateData("Idaho", 4.81, 0),
  Illinois: new StateData("Illinois", 3.14, 0),
  Indiana: new StateData("Indiana", 4.21, 0),
  Kansas: new StateData("Kansas", 4.57, 0),
  Kentucky: new StateData("Kentucky", 4.94, 0),
  Louisiana: new StateData("Louisiana", 4.83, 0),
  Massachusetts: new StateData("Massachusetts", 4.06, 0),
  Maryland: new StateData("Maryland", 4.47, 0),
  Maine: new StateData("Maine", 4.35, 0),
  Michigan: new StateData("Michigan", 4.1, 0),
  Minnesota: new StateData("Minnesota", 4.53, 0),
  Missouri: new StateData("Missouri", 4.56, 0),
  Mississippi: new StateData("Mississippi", 4.43, 0),
  Montana: new StateData("Montana", 4.69, 0),
  NewMexico: new StateData("New Mexico", 6.77, 0),
  Nebraska: new StateData("Nebraska", 4.85, 0),
  NorthCarolina: new StateData("North Carolina", 5.01, 0),
  NorthDakota: new StateData("North Dakota", 5.01, 0),
  NewJersey: new StateData("New Jersey", 4.21, 0),
  Nevada: new StateData("Nevada", 6.2, 0),
  NewYork: new StateData("New York", 3.79, 0),
  Ohio: new StateData("Ohio", 4.04, 0),
  Oklahoma: new StateData("Oklahoma", 5.29, 0),
  Oregon: new StateData("Oregon", 4.43, 0),
  Pennsylvania: new StateData("Pennsylvania", 3.6, 0),
  RhodeIsland: new StateData("Rhode Island", 4.23, 0),
  SouthCarolina: new StateData("South Carolina", 5.06, 0),
  SouthDakota: new StateData("South Dakota", 5.23, 0),
  Tennessee: new StateData("Tennessee", 4.41, 0),
  Texas: new StateData("Texas", 5.77, 0),
  Utah: new StateData("Utah", 5.55, 0),
  Virginia: new StateData("Virginia", 4.13, 0),
  Washington: new StateData("Washington", 4.33, 0),
  Wisconsin: new StateData("Wisconsin", 4.29, 0),
  WestVirginia: new StateData("West Virginia", 3.65, 0),
  Wyoming: new StateData("Wyoming", 6.06, 0),
};
